// Seeds the curated image catalog. The image files themselves live in the
// frontend at public/catalog/*.svg (generated by
// frontend/scripts/generate-catalog-images.mjs) — the DB only stores paths.
// Keywords carry Swahili + English synonyms so vendor search finds them
// either way (e.g. "maharage" -> beans).
const IMAGES = [
  { name: "Maize", keywords: "mahindi,corn,nafaka", url: "/catalog/maize.svg" },
  { name: "Beans", keywords: "maharage,haricot,kunde", url: "/catalog/beans.svg" },
  { name: "Rice", keywords: "mchele,mpunga", url: "/catalog/rice.svg" },
  { name: "Tomatoes", keywords: "nyanya", url: "/catalog/tomatoes.svg" },
  { name: "Onions", keywords: "vitunguu", url: "/catalog/onions.svg" },
  { name: "Potatoes", keywords: "viazi,viazi mviringo", url: "/catalog/potatoes.svg" },
  { name: "Bananas", keywords: "ndizi,migomba", url: "/catalog/bananas.svg" },
  { name: "Cassava", keywords: "mihogo,muhogo", url: "/catalog/cassava.svg" },
  { name: "Sunflower", keywords: "alizeti,mafuta", url: "/catalog/sunflower.svg" },
  { name: "Coffee", keywords: "kahawa,buni", url: "/catalog/coffee.svg" },
  { name: "Cashew", keywords: "korosho", url: "/catalog/cashew.svg" },
  { name: "Avocado", keywords: "parachichi", url: "/catalog/avocado.svg" },
  { name: "Watermelon", keywords: "tikiti,tikiti maji", url: "/catalog/watermelon.svg" },
  { name: "Chicken", keywords: "kuku,broiler,kienyeji", url: "/catalog/chicken.svg" },
  { name: "Goat", keywords: "mbuzi", url: "/catalog/goat.svg" },
  { name: "Cattle", keywords: "ng'ombe,ngombe,cow,maksai", url: "/catalog/cattle.svg" },
  { name: "Fish", keywords: "samaki,dagaa,sato", url: "/catalog/fish.svg" },
  { name: "Eggs", keywords: "mayai", url: "/catalog/eggs.svg" },
  { name: "Milk", keywords: "maziwa", url: "/catalog/milk.svg" },
  { name: "Tractor", keywords: "trekta,plau,kulima", url: "/catalog/tractor.svg" },
  { name: "Water Pump", keywords: "pampu,maji,umwagiliaji", url: "/catalog/water-pump.svg" },
  { name: "Fertilizer", keywords: "mbolea,samadi", url: "/catalog/fertilizer.svg" },
  { name: "Seeds", keywords: "mbegu,nafaka", url: "/catalog/seeds.svg" },
  { name: "Pesticide Sprayer", keywords: "dawa,kunyunyizia,bomba la dawa", url: "/catalog/sprayer.svg" },
  { name: "Agronomist Advice", keywords: "ushauri,mtaalamu wa kilimo,agronomy", url: "/catalog/agronomist.svg" },
  { name: "Crop Doctor", keywords: "daktari wa mimea,magonjwa ya mimea", url: "/catalog/crop-doctor.svg" },
  { name: "Farm Labor", keywords: "kibarua,vibarua,wafanyakazi", url: "/catalog/farm-labor.svg" },
  { name: "Irrigation Service", keywords: "umwagiliaji,drip,maji", url: "/catalog/irrigation.svg" },
];

exports.up = async function (knex) {
  for (const image of IMAGES) {
    const existing = await knex("catalog_images").where({ url: image.url }).first();
    if (!existing) {
      await knex("catalog_images").insert(image);
    }
  }
};

exports.down = async function (knex) {
  await knex("catalog_images")
    .whereIn("url", IMAGES.map((i) => i.url))
    .del();
};
