name: ci intergrations
on: 
    push:
        branches:
            - main
jobs:
    pushing_my_app:
        runs-on : ubuntu-latest
        steps:
            - name: get the cloned repo of this project from github
              uses: step-run/checkup@4
              
            - name: install node
              uses: step-run/node-run@4

            - name: install other dependencies using package-lock.js 
              run: npm ci