name: second CI
on:
    push:
        branches:
            - main
jobs:
    create-app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with: 
                node-version: 22

            - name: run npm install using ci(using the package-lock.json)
              run: echo "npm ci"