name:
  app-name-CI
on:
  push:
    branches:
      - main
jobs:
  CI-CD:
    runs-on: ubuntu-latest

    env:
      MYSQL_ROOT_PASSWORD: aaa
      MYSQL_DATABASE: aaa
      #etc -- I am saving time 

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: aaa
          MYSQL_DATABASE: aaa
        options:

    steps:
      - name: get app
        uses: actions/checkout@v4
      - name: install node
        uses: actions/node-run@v4
        with:
          node-version: 24
      - name: prep app with packs installation
        run: npm ci
      - name: run migrations
        run: npm knex migrate:latest
      - name: run tests
        run:  npx vitest
      - name: now if CI passes now it is the time to run ssh command
        run: echo secret.agrigax_ssh_prevate > secret_file
      - name: finally run the ssh using the secret_file
        run: ssh -i secret_file deploy@192.168.0.2 
