name: CI unyama
on:
  push:
    branches:
      -  main
jobs: 
  unyama:
    runs-on: ubuntu-latest
    steps:
      - name: single command app cloning
        uses: actions/checkout@v4

      - name: installing node 
        uses: actions/setup-node@v4
        with:
            node-version: 22
      
      - name: install npm
        working-directory: agrigax_backend
        run: npm ci
        


